test: &default

  # Credentials for REST APIs
  client_id: ENV["PAYPAL_PUBLIC"]
  client_secret: ENV["PAYPAL_SECRET"]

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
